import Foundation

/// Generates a human-readable Markdown model card next to a checkpoint —
/// architecture, dataset/training context, metrics, and known limitations.
enum ModelCard {
    static func generate(meta: Checkpoint.Meta, hardware: HardwareInfo, datasetName: String?, method: String) -> String {
        let df = DateFormatter(); df.dateStyle = .medium; df.timeStyle = .short
        var s = "# Model Card\n\n"
        s += "Generated by LabLLM on \(df.string(from: meta.createdAt)).\n\n"

        s += "## Architecture\n"
        s += "- Type: GPT-style decoder-only transformer\n"
        s += "- Layers: \(meta.config.nLayers)\n"
        s += "- Hidden dimension: \(meta.config.nEmbd)\n"
        s += "- Attention heads: \(meta.config.nHeads)\n"
        s += "- Context length: \(meta.config.blockSize)\n"
        s += "- MLP ratio: \(meta.config.mlpRatio)\n"
        s += "- Weight tying: \(meta.config.tieWeights ? "yes" : "no")\n"
        s += "- Parameters (approx.): \(format(meta.config.estimatedParameters))\n\n"

        s += "## Tokenizer\n"
        s += "- Kind: \(meta.tokenizer.kind.label)\n"
        s += "- Vocabulary size: \(meta.tokenizer.vocabSize)\n\n"

        s += "## Training\n"
        s += "- Method: \(method)\n"
        s += "- Steps completed: \(meta.step)\n"
        s += "- Final train loss: \(String(format: "%.4f", meta.loss))\n"
        if meta.valLoss > 0 { s += "- Final val loss: \(String(format: "%.4f", meta.valLoss))\n" }
        if let d = datasetName { s += "- Dataset: \(d)\n" }
        s += "\n"

        s += "## Hardware\n"
        s += "- Trained on: \(hardware.chip)\n"
        s += "- Unified memory: \(String(format: "%.0f", hardware.physicalMemoryGB)) GB\n\n"

        s += "## Limitations\n"
        s += "- Small local model trained for demonstration/learning purposes, not production use.\n"
        s += "- May produce inaccurate, repetitive, or nonsensical output, especially outside its training distribution.\n"
        s += "- Not evaluated for safety, bias, or factual reliability.\n\n"

        s += "## Intended use\n"
        s += "Local experimentation and learning about how small language models are trained. Not intended for deployment.\n"
        return s
    }

    private static func format(_ n: Int) -> String {
        let f = NumberFormatter(); f.numberStyle = .decimal
        return f.string(from: NSNumber(value: n)) ?? "\(n)"
    }
}
